# Generated by Django 6.0.4 on 2026-04-16 23:20

import django.utils.timezone
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='Unique ID in UUID v7 format.', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Name for the profile.', max_length=255)),
                ('gender', models.CharField(blank=True, help_text='Predicted gender.', max_length=50, null=True)),
                ('gender_probability', models.FloatField(blank=True, help_text='Probability of the predicted gender.', null=True)),
                ('sample_size', models.IntegerField(blank=True, help_text='Sample size for gender prediction.', null=True)),
                ('age', models.IntegerField(blank=True, help_text='Predicted age.', null=True)),
                ('age_group', models.CharField(blank=True, help_text='Classified age group (child, teenager, adult, senior).', max_length=50, null=True)),
                ('country_id', models.CharField(blank=True, help_text='Predicted country ID.', max_length=10, null=True)),
                ('country_probability', models.FloatField(blank=True, help_text='Probability of the predicted country.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of creation in UTC ISO 8601 format.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
